# Generated by Django 3.2 on 2021-04-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='logout',
            name='logout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.login'),
            preserve_default=False,
        ),
    ]
